apiVersion: skaffold/v3
kind: Config
metadata:
  name: starter-spring-boot
build:
  artifacts:
  - image: sergioamim/demo-starter-spring-boot
    jib: {}
manifests:
  rawYaml:
  - k8s/deployment.yaml
  - k8s/service.yaml
  - k8s/ingress.yaml
